openapi: 3.0.0
info:
  title: Documentation de l'API
  description: Documentation complète de l'API
  version: 1.0.0

servers:
  - url: http://localhost:5000/api/v1
    description: Serveur de développement

paths:
  /post/getPostById/{id}:
    get:
      summary: Obtenir un post par ID
      tags:
        - Post
      parameters:
        - name: id
          in: path
          required: true
          description: ID du post à obtenir
          schema:
            type: string
      responses:
        '200':
          description: Post récupéré avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Post non trouvé

  /post/create:
    post:
      summary: Créer un nouveau post
      tags:
        - Post
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '201':
          description: Post créé avec succès
        '400':
          description: Requête invalide

  /post/delete:
    post:
      summary: Supprimer un post
      tags:
        - Post
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required:
                - id
      responses:
        '200':
          description: Post supprimé avec succès
        '404':
          description: Post non trouvé

  /post/update:
    post:
      summary: Mettre à jour un post
      tags:
        - Post
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '200':
          description: Post mis à jour avec succès
        '404':
          description: Post non trouvé

  /post/likePost/{id}:
    post:
      summary: Aimer un post
      tags:
        - Post
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID du post à aimer
          schema:
            type: string
      responses:
        '200':
          description: Post aimé avec succès
        '404':
          description: Post non trouvé

  /post/dislikePost/{id}:
    post:
      summary: Ne pas aimer un post
      tags:
        - Post
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID du post à ne pas aimer
          schema:
            type: string
      responses:
        '200':
          description: Post non aimé avec succès
        '404':
          description: Post non trouvé

  /post/getAllPosts:
    get:
      summary: Obtenir tous les posts
      tags:
        - Post
      responses:
        '200':
          description: Liste des posts récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'

  /post/notePost:
    get:
      summary: Noter un post
      tags:
        - Post
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Post noté avec succès

  /post/comment/{idPost}:
    get:
      summary: Obtenir les commentaires d'un post
      tags:
        - Post
      parameters:
        - name: idPost
          in: path
          required: true
          description: ID du post dont obtenir les commentaires
          schema:
            type: string
      responses:
        '200':
          description: Commentaires récupérés avec succès

  /post/comment/{idPost}/{idComment}:
    delete:
      summary: Supprimer un commentaire d'un post
      tags:
        - Post
      security:
        - bearerAuth: []
      parameters:
        - name: idPost
          in: path
          required: true
          description: ID du post
          schema:
            type: string
        - name: idComment
          in: path
          required: true
          description: ID du commentaire à supprimer
          schema:
            type: string
      responses:
        '200':
          description: Commentaire supprimé avec succès
        '404':
          description: Commentaire ou post non trouvé

  /post/comment/{idPost}/{idComment}/reponse:
    post:
      summary: Répondre à un commentaire d'un post
      tags:
        - Post
      security:
        - bearerAuth: []
      parameters:
        - name: idPost
          in: path
          required: true
          description: ID du post
          schema:
            type: string
        - name: idComment
          in: path
          required: true
          description: ID du commentaire
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reply:
                  type: string
              required:
                - reply
      responses:
        '200':
          description: Réponse ajoutée avec succès

  /post/comment/{idPost}/{idComment}/reponse/{idReply}:
    delete:
      summary: Supprimer une réponse à un commentaire d'un post
      tags:
        - Post
      security:
        - bearerAuth: []
      parameters:
        - name: idPost
          in: path
          required: true
          description: ID du post
          schema:
            type: string
        - name: idComment
          in: path
          required: true
          description: ID du commentaire
          schema:
            type: string
        - name: idReply
          in: path
          required: true
          description: ID de la réponse à supprimer
          schema:
            type: string
      responses:
        '200':
          description: Réponse supprimée avec succès
        '404':
          description: Réponse, commentaire ou post non trouvé

  /post/repost/{idPost}:
    post:
      summary: Reposter un post
      tags:
        - Post
      security:
        - bearerAuth: []
      parameters:
        - name: idPost
          in: path
          required: true
          description: ID du post à reposter
          schema:
            type: string
      responses:
        '200':
          description: Post republié avec succès
        '404':
          description: Post non trouvé

  /post/repost/{idPost}:
    delete:
      summary: Supprimer un repost
      tags:
        - Post
      security:
        - bearerAuth: []
      parameters:
        - name: idPost
          in: path
          required: true
          description: ID du post à supprimer du repost
          schema:
            type: string
      responses:
        '200':
          description: Repost supprimé avec succès
        '404':
          description: Post non trouvé

  /post/report/{postId}:
    post:
      summary: Signaler un post
      tags:
        - Post
      security:
        - bearerAuth: []
      parameters:
        - name: postId
          in: path
          required: true
          description: ID du post à signaler
          schema:
            type: string
      responses:
        '200':
          description: Post signalé avec succès
        '404':
          description: Post non trouvé

  /post/share:
    post:
      summary: Partager un post
      tags:
        - Post
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  type: string
              required:
                - postId
      responses:
        '200':
          description: Post partagé avec succès

  /post/view/{postId}:
    post:
      summary: Voir un post
      tags:
        - Post
      security:
        - bearerAuth: []
      parameters:
        - name: postId
          in: path
          required: true
          description: ID du post à voir
          schema:
            type: string
      responses:
        '200':
          description: Post vu avec succès
        '404':
          description: Post non trouvé

  /users/register:
    post:
      summary: Enregistrer un nouvel utilisateur
      tags:
        - Utilisateurs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Utilisateur créé avec succès
        '400':
          description: Requête invalide

  /users/login:
    post:
      summary: Connexion d'un utilisateur
      tags:
        - Utilisateurs
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Connexion réussie
        '401':
          description: Identifiants invalides

  /users/deleteAccount:
    delete:
      summary: Supprimer le compte d'un utilisateur
      tags:
        - Utilisateurs
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email
      responses:
        '200':
          description: Compte supprimé avec succès
        '404':
          description: Compte non trouvé

  /users/updateProfile:
    post:
      summary: Mettre à jour le profil utilisateur
      tags:
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                bio:
                  type: string
                avatar:
                  type: string
              required:
                - name
      responses:
        '200':
          description: Profil mis à jour avec succès
        '400':
          description: Requête invalide

  /users/getProfile:
    get:
      summary: Obtenir le profil utilisateur
      tags:
        - Utilisateurs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profil utilisateur récupéré avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Profil non trouvé

  /users/follow/{userId}:
    post:
      summary: Suivre un utilisateur
      tags:
        - Utilisateurs
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          description: ID de l'utilisateur à suivre
          schema:
            type: string
      responses:
        '200':
          description: Utilisateur suivi avec succès
        '404':
          description: Utilisateur non trouvé

  /users/unfollow/{userId}:
    post:
      summary: Ne plus suivre un utilisateur
      tags:
        - Utilisateurs
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          description: ID de l'utilisateur à ne plus suivre
          schema:
            type: string
      responses:
        '200':
          description: Utilisateur n'est plus suivi avec succès
        '404':
          description: Utilisateur non trouvé

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Post:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string
        authorId:
          type: string
        likes:
          type: integer
        dislikes:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - title
        - content
        - authorId

    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        bio:
          type: string
        avatar:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - name
        - email

